import requests
import json
for n in range(11):
    url2='https://compass.umeng.com/api/phone/dt?reportId=10010101&platform=all'
    html2=requests.get(url2)
    h2=html2.json()
    ds=h2['data']['data'][0]['data'][n]['ds']
    percentage_android=h2['data']['data'][1]['data'][n]['percentage']
    percentage_ios=h2['data']['data'][0]['data'][n]['percentage']
    url='https://compass.umeng.com/api/phone/dt?reportId=10010101&sex=all'
    ht1=requests.get(url)
    h1=ht1.json()
    percentage_woman=h1['data']['data'][0]['data'][n]['percentage']
    percentage_man=h1['data']['data'][1]['data'][n]['percentage']
    url3='https://compass.umeng.com/api/phone/dt?reportId=10010101&age=all'
    ht3=requests.get(url3)
    h3=ht3.json()
    percentage0=h3['data']['data'][0]['data'][n]['percentage']
    percentage1=h3['data']['data'][1]['data'][n]['percentage']
    percentage2=h3['data']['data'][2]['data'][n]['percentage']
    percentage3=h3['data']['data'][3]['data'][n]['percentage']
    percentage4=h3['data']['data'][4]['data'][n]['percentage']
    percentage5=h3['data']['data'][5]['data'][n]['percentage']
    percentage6=h3['data']['data'][6]['data'][n]['percentage']
    url4='https://compass.umeng.com/api/phone/dt?reportId=10010101&city=all'
    ht4=requests.get(url4)
    h4=ht4.json()
    percentage_city0=h4['data']['data'][0]['data'][n]['percentage']
    percentage_city1=h4['data']['data'][1]['data'][n]['percentage']
    percentage_city2=h4['data']['data'][2]['data'][n]['percentage']
    percentage_city3=h4['data']['data'][3]['data'][n]['percentage']
    percentage_city4=h4['data']['data'][4]['data'][n]['percentage']
    percentage_city5=h4['data']['data'][5]['data'][n]['percentage']
    url5='https://compass.umeng.com/api/phone/dt?reportId=10010101&area=all'
    ht5=requests.get(url5)
    h5=ht5.json()
    area0=h5['data']['data'][0]['data'][n]['percentage']
    area1=h5['data']['data'][1]['data'][n]['percentage']
    area2=h5['data']['data'][2]['data'][n]['percentage']
    area3=h5['data']['data'][3]['data'][n]['percentage']
    area4=h5['data']['data'][4]['data'][n]['percentage']
    area5=h5['data']['data'][5]['data'][n]['percentage']
    area6=h5['data']['data'][6]['data'][n]['percentage']
    url6='https://compass.umeng.com/api/phone/dt?reportId=10010101'
    ht6=requests.get(url6)
    h6=ht6.json()
    total0=h6['data']['data'][0]['data'][n]['value']
    print('总体'+'\t'+str(total0)+'\t'+str(ds))
    print('平台'+'\t'+'android'+'\t'+str(percentage_android)+'%\t'+str(ds))
    print('平台'+'\t'+'ios'+'\t'+str(percentage_ios)+'%\t'+str(ds))
    print('性别'+'\t'+'男'+'\t'+str(percentage_man)+'%\t'+str(ds))
    print('性别'+'\t'+'女'+'\t'+str(percentage_woman)+'%\t'+str(ds))
    print('年龄'+'\t'+'<20岁'+'\t'+str(percentage0)+'%\t'+str(ds))
    print('年龄'+'\t'+'20-24岁'+'\t'+str(percentage1)+'%\t'+str(ds))
    print('年龄'+'\t'+'25-29岁'+'\t'+str(percentage2)+'%\t'+str(ds))
    print('年龄'+'\t'+'30-34岁'+'\t'+str(percentage3)+'%\t'+str(ds))
    print('年龄'+'\t'+'35-39岁'+'\t'+str(percentage4)+'%\t'+str(ds))
    print('年龄'+'\t'+'40-49岁'+'\t'+str(percentage5)+'%\t'+str(ds))
    print('年龄'+'\t'+'50+岁'+'\t'+str(percentage6)+'%\t'+str(ds))
    print('城市'+'\t'+'一线'+'\t'+str(percentage_city0)+'%\t'+str(ds))
    print('城市'+'\t'+'二线'+'\t'+str(percentage_city1)+'%\t'+str(ds))
    print('城市'+'\t'+'三线'+'\t'+str(percentage_city2)+'%\t'+str(ds))
    print('城市'+'\t'+'四线'+'\t'+str(percentage_city3)+'%\t'+str(ds))
    print('城市'+'\t'+'五线'+'\t'+str(percentage_city4)+'%\t'+str(ds))
    print('城市'+'\t'+'六线'+'\t'+str(percentage_city5)+'%\t'+str(ds))
    print('区域'+'\t'+'华东'+'\t'+str(area0)+'%\t'+str(ds))
    print('区域'+'\t'+'华北'+'\t'+str(area0)+'%\t'+str(ds))
    print('区域'+'\t'+'华中'+'\t'+str(area0)+'%\t'+str(ds))
    print('区域'+'\t'+'华南'+'\t'+str(area0)+'%\t'+str(ds))
    print('区域'+'\t'+'西南'+'\t'+str(area0)+'%\t'+str(ds))
    print('区域'+'\t'+'西北'+'\t'+str(area0)+'%\t'+str(ds))
    print('区域'+'\t'+'东北'+'\t'+str(area0)+'%\t'+str(ds))
